export const FETCH_HOTDOGS = "HOTDOG/FETCH_HOTDOGS";
export const CREATE_HOTDOG = "HOTDOG/CREATE_HOTDOG";
export const DELETE_HOTDOG = "HOTDOG/DELETE_HOTDOG";
export const UPDATE_HOTDOG = "HOTDOG/UPDATE_HOTDOG";

export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const SHOW_MODAL = "APP/SHOW_MODAL";
export const HIDE_MODAL = "APP/HIDE_MODAL";